'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PUNTO_DE_VENTA_MAGBRICORP.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property advertencia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("advertencia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property calendario() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("calendario", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property candado() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("candado", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Candy_Candy_candy_candy_9421203_572_508() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Candy-Candy-candy-candy-9421203-572-508", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property carrito_de_tienda_online() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("carrito_de_tienda_online", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cerveza() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cerveza", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property clip() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("clip", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property COBROSSSS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("COBROSSSS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        '''&lt;database DBcnString=&quot;pp/IDbr4hCWnoNgvP1egROlPrezDr1dCJV0bYoOY8GXyZ1AKNb/CJV9qmLoShAp6Ur0WZRSARNyNdRUqlb6zSrT9rnF8HYuK3ARP08mTHkdi2Q6oPi5Vy1krRiUwnm+kc3thO/go8aOc36Gh0GUtmCKFzYwzViJc4mwtrth1nfdDXkbPiysDjnA+1bwJqtaeNXFvXIKMqnXc8byYHi1SDKf/7y0KQguJpaZHMBt8TJbt/K8ZkjF5v/osxccREPf+sWq6OGhDhtBRShKkauoZ9EZ5srC1AjhfBdJW3Gk741n+ehfWOwqTowrs/h+6LARzOLpt/eWhokVvNG7MEihrD1NpLddTUtuPlUD8tskFemYYlXHxBgZ4HDdUeH1Yp1iOpgasN1/elrUuKdkTQXeMCIMuXm/iLBMMPbXerrtw5s1FfsHaEvH6j7w3IBupbzw6gdgwzvZMK4p/BcHxunn [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property Conexion_web() As String
            Get
                Return ResourceManager.GetString("Conexion_web", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property config_redentor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("config_redentor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        '''&lt;database DBcnString=&quot;WallmZ7YHDK8U02EwUpscheqpesUKMI/Nexe1RFXtmsl8T0EDvDmqGLuhVc03x74mrsJvo3lZW5GXSxEJnJuwWx01Z1to3MTHo7pUTh6qs3uaPI7MRNUxbh7NonrSxwluhhpZOGDItrAbx73w+MhR6oeaGMNj7kMagGEZU8p5AjLamfaw5eAUHTkZJ2CuqgKuYUM1QLY9bz7ookoPcNcxySE80u4t4p8H+CJgevPT/G+zvLC/xDrPBAvRo/0zOSvpGnWe6AzE1sV8xGk1cxI600ZB4rWwKt2x4IrKbfC9P6U09dX6oGDx/V1iPC8pBoP&quot;&gt;
        '''&lt;/database&gt;.
        '''</summary>
        Friend ReadOnly Property ConnectionString() As String
            Get
                Return ResourceManager.GetString("ConnectionString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property etiqueta() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("etiqueta", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gogeta() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gogeta", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property goku() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("goku", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gokuqueda() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gokuqueda", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property homero() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("homero", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_BLACK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_BLACK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property megafono() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("megafono", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property menu_BLACK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("menu_BLACK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Menu_redentor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Menu_redentor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property monedas() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("monedas", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property monster() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("monster", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property naruto() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("naruto", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property notificacion_BLACK2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("notificacion_BLACK2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property notificacion_redentor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("notificacion_redentor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nube_secundaria() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nube_secundaria", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nube_sincroizacio() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nube_sincroizacio", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pacman() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pacman", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sakura() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sakura", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        '''&lt;database DBcnString=&quot;0V29dUgDgFBlgwafgkq4YfCg9DbQnA1bhscSNx2dICw=&quot;&gt;
        '''&lt;/database&gt;.
        '''</summary>
        Friend ReadOnly Property Serial_ff() As String
            Get
                Return ResourceManager.GetString("Serial_ff", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        '''&lt;database DBcnString=&quot;KeoBMN8xW1kDVyWyS0YeO+ogtB5d2NAvSBS1EDoj+sA=&quot;&gt;
        '''&lt;/database&gt;.
        '''</summary>
        Friend ReadOnly Property Serial_l() As String
            Get
                Return ResourceManager.GetString("Serial_l", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot;?&gt;
        '''&lt;database DBcnString=&quot;KeoBMN8xW1kDVyWyS0YeO9AomrzTEtjYZRRadNMcigk=&quot;&gt;
        '''&lt;/database&gt;.
        '''</summary>
        Friend ReadOnly Property Serial_x() As String
            Get
                Return ResourceManager.GetString("Serial_x", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a USE [RRRR]
        '''
        '''GO
        '''CREATE TABLE [dbo].[ASISTENCIAS](
        '''	[Id_asistencia] [int] IDENTITY(1,1) NOT NULL,
        '''	[Id_personal] [int] NULL,
        '''	[Fecha_entrada] [datetime] NULL,
        '''	[Fecha_salida] [datetime] NULL,
        '''	[Estado] [varchar](50) NULL,
        '''	[Horas] [numeric](18, 2) NULL,
        ''' CONSTRAINT [PK_ASISTENCIAS] PRIMARY KEY CLUSTERED 
        '''(
        '''	[Id_asistencia] ASC
        ''')WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
        ''') ON [PRIMARY]
        '''
        '''GO
        '''SET ANSI_PADDIN [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property SqlBasemackeys() As String
            Get
                Return ResourceManager.GetString("SqlBasemackeys", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
